spring:
  redis:
    uri:  redis://default:dsW7l1XBytx5DzokmUisBe71NaZ8lISC@redis-17843.c244.us-east-1-2.ec2.redns.redis-cloud.com:17843
  application:
    name: journalApp
  data:
    mongodb:
      uri: mongodb+srv://pundirmudit1:rxIiP9JhkYjlFiHJ@cluster0.d8hvp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pundirmudit1@gmail.com
    password: atho nnsp jfrv gcdm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true







server:
  port: 8080

weather_api:  9c6db8dde1928cd052d5cb851dc80c16



